### ISSUE TITLE
你的博客是放在 github的吗？

### ISSUE THREAD

**Issue by vmvz** [xcatliu/hexo-theme-lite#1]
看IP是荷兰的，

速度很快呀

**Comment by vmvz** [comment]
再用 ipip net 查询了一下，发现是 www.fastly.com 的 cdn？

**Comment by xcatliu** [comment]
我的域名 xcatliu.com 是在 https://www.name.com/ 注册的，网站是直接放在了 [GitHub Pages](https://pages.github.com/) 上了

**Comment by vmvz** [comment]
奇怪，为什么你的博客速度为什么这么快

**Comment by xcatliu** [comment]
@vmvz 可能是你的网络比较好吧~
博客的 GitHub 地址在这里： https://github.com/xcatliu/blog
